name: Build Ubuntu
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: INSTALL_ADDITIONAL_BUILD_DEPENDENCIES
      run: |
         sudo apt install -y eatmydata
         sudo eatmydata apt-get install librtlsdr-dev libusb-dev libxml2-dev libxslt1-dev
    - id: CONFIGURE
      run: eatmydata ./configure
    - id: MAKE
      run: eatmydata make
    - id: TEST
      run: eatmydata make test
